dataforgoodfr/12_bloom

src/infra/marine_traffic_scraper.py

`MarineTrafficVesselScraper.base_url` n'était pas utilisée dans la définition du `vessel_url`, impliquant une redéfinition de la même chaîne de caractère.

Fix duplicate base_url vessel definition

---

bloom/domain/vessel.py
bloom/infra/marine_traffic_scraper.py
tests/infra/test_marine_traffic_scrapper.py

En parcourant les colonnes mises à disposition par MarineTraffic, certaines semblent intéressantes à rajouter pour la génération d'alertes : 
- Statut
- Vitesse instantanée
- [Statut de navigation](https://help.marinetraffic.com/hc/en-us/articles/203990998-What-is-the-significance-of-the-AIS-Navigational-Status-Values-)
D'autres colonnes sont disponibles : 
- Photos
- Destination Port
- Reported ETA
- Reported Destination
- Current Port
- Vessel Type - Generic
- Time of Latest Position
- Course
- Width
- Capacity - DWT
- Current Port UNLOCODE
- Current Port Country
- Callsign

feat: add speed, status & navigation_status to vessel scrapping

---

.env.template
bloom/config.py
bloom/infra/database/sql_model.py

Avoid error "Wrong schema" when using load mpa on the application. 
It fixes function get_closest_marine_protected_areas() that use the sql_model MPA.
Also, I remove duplicates variables for POSTGRES_HOSTNAME / POSTGRES_PORT. Differences between using Docker or not should be in values of these variables not by duplicating variables.

Fix load mpa

---

alembic/init_script/load_amp_data.py
alembic/init_script/load_positions_data.py
alembic/init_script/load_vessels_data.py
docker-env/Dockerfile
docker-env/entrypoint.sh

* add container.py to Dockerfile avoiding  No module named 'container' at runtime error
* add root userin cron_scrapper avoiding user missing error at runtime
* modify the way ENV vars are shared between Docker root terminal and cron process storing env parameters in ~/.env and loading them in cron line
* add packages needed for python version > 3.11 and package compilation
* modify the path of data in alembic/init_script/load_*, using relative path from script instead of CWD that could be different from projet home in Docker and host native installation
* (re) activation of entreypoint/cmd dockerfile to get a docker container running as a production one instead of python shell
* remove the print of db_url values, avoiding password presence in console logs and docker logs
QUESTION: What …

Docker various fixes

---

bloom/bloom/domain/alert.py
bloom/bloom/domain/vessel.py
bloom/bloom/infra/http/marine_traffic_scraper.py
bloom/bloom/infra/repositories/repository_vessel.py

To conforme to Data For Good preconisation to support all LTS python versions (3.8-3.12 today), the modification is to use syntax compliante with 3.9
geopandas has restriction to use python version >=3.9 <3.12 and for 3.9.7 specific version
pyproject.toml is taking account about these constraints

[02] fix: Python 3.9 syntax compatibility

---

.github/workflows/build.yaml

J'y ai pensé après mais oublié de remettre à jour le github action de build avec le bon chemin vers le Dockerfile

fix: github action build docker => docker-env => docker/Dockerfile

---

.github/workflows/version_supports.yaml
docker/Dockerfile

Try to install POETRY for python versions 3.8, 3.9, 3.10, 3.11, 3.12
* 3.12 is failing because of dependency_injection package not compliant with 3.12
* 3.8 is installing with no error but poetry should not permit this kind of installation as geopandas as a python >= 3.9 restriction
* 3.11 is installing with no error but is taking a really long time to install, maybe linked to compilation and add of 2 prerequisite gcc and libgeos-dev

Add githubs actions to check compiance with LTS python versions 3.9-3.11

---

docker-compose-load-data.yaml

Ajout de la tâche compute_port_geometry_buffer dans la procédure docker-compose-load-data

docker: ajout compute_port_geometry_buffer dans procédure load with data

---

backend/bloom/domain/api.py
backend/bloom/domain/metrics.py
backend/bloom/infra/database/sql_model.py
backend/bloom/routers/metrics.py
backend/bloom/routers/ports.py
backend/bloom/routers/vessels.py
backend/bloom/routers/zones.py
backend/bloom/services/api.py

METRICS ENDPOINTS
- /metrics/vessels-in-activity/total/{start_at/{end_at}
- /metrics/zone-visited/total/{start_at/{end_at}metrics
- /zones/{zone_id}/{zone_types}/visit?limit=N&orderBy=ASC/DESC  > renvoie le visiting time pour les top N vessels dans touts les zones/la zone_id
- /vessels/{vessel_id}/{visit_types|all}/visit?limit=N&orderBy=ASC/DESC  > renvoie le visiting time pour les top N zones pour tous les vessel/le vessel_id
-  ADD temporal filters (start_at, end_at) as Timestamps (start/end included ? GMT+0 ?)
-  define what is the "most visited" criteria

[FEAT] Add dashboard metric endpoints #204

---

backend/bloom/container.py
backend/bloom/routers/metrics.py
backend/bloom/services/metrics.py

Création d'un service Metrics pour centraliser les requêtes complexes sur les différents model repositories et simplifier les appels côté API

refacto: create MetricsService based on model repositories

---

backend/bloom/main.py
backend/bloom/routers/v1/cache.py
backend/bloom/routers/v1/metrics.py
backend/bloom/routers/v1/ports.py
backend/bloom/routers/v1/vessels.py
backend/bloom/routers/v1/zones.py

Ajout d'un prefix /api/v1/... pour tous les endpoints
- /api/v1/cache/all/flush
- /api/v1/metrics/vessels-in-activity
- /api/v1/metrics/zone-visited
- /api/v1/metrics/zones/{zone_id}/visiting-time-by-vessel
- /api/v1/metrics/vessels/{vessel_id}/activity/{activity_type}
- /api/v1/ports
- /api/v1/ports/{port_id}
- /api/v1/vessels
- /api/v1/vessels/{vessel_id}
- /api/v1/vessels/all/positions/last
- /api/v1/vessels/{vessel_id}/positions/last
- /api/v1/vessels/{vessel_id}/excursions
- /api/v1/vessels/{vessel_id}/excursions/{excursions_id}
- /api/v1/vessels/{vessel_id}/excursions/{excursions_id}/segments
- /api/v1/vessels/{vessel_id}/excursions/{excursions_id}/segments/{segment_id}
- /api/v1/zones
- /api/v1/zones/all/categories
- /api/v1/zones/by-category/{category}/by-sub-category/{sub}
- …

feat: add /api/v1 prefix for all API endpoints in prevision of multiple versions

---

frontend/components.json
frontend/components/providers/map-store-provider.tsx
frontend/components/providers/vessels-store-provider.tsx
frontend/components/ui/button.tsx
frontend/components/ui/command.tsx
frontend/components/ui/dialog.tsx
frontend/libs/fonts.ts
frontend/libs/stores/map-store.ts
frontend/libs/stores/vessels-store.ts
frontend/libs/utils.ts
frontend/prettier.config.js

fix: rename /lib to /libs, so it is no longer ignored

fix(frontend): correct compile error due to missing /lib folder

---

docker/Dockerfile

une erreur à la construction de l'image docker liée à UV
il semble que le comosant cargo n'est plus utilisé et le chargement du fichier ~/.cargo/env génère donc une erreur après installation uv
Le fix consiste simplement à supprimer cette ligne
validé pour des images docker pyhton 3.10 et 3.11

fix: docker build

---

backend/bloom/services/metrics.py

Des restes de tests de vues retreintes pour les bateaux qui renvoyait un VesselListView au lieu d'un Vessel tout court avec toutes les infos (entre un peu en conflit avec la suppression des données géométrie sur laquelle bosse @SaboniAmine #282 )

fix: no IMO in vessel activity

---

backend/bloom/dependencies.py

Utilisation du json encoder de fastapi qui plus complet que celui de base pour le remplissage du cache notamment pour traiter les custom types comme les segments

fix: TypeError: Object of type Segment is not JSON serializable

---

backend/bloom/domain/vessel.py

fix: 272 [API] endpoint visiting_time_by_vessel : manque MMSI et IMO

---

backend/bloom/infra/repositories/repository_vessel.py
backend/bloom/routers/v1/vessels.py

Permet de récupérer le nombre de bateau trackés actuellement
Suite discussion @alexphiev 
lié à l'issue #245

feat: ajout endpoint /api/v1/vessels/trackedCount

---

backend/bloom/tasks/load_dim_zone_amp_from_csv.py

rajouter une élément à charger dans load_dim_zone_amp_from_csv.py
Le fichier est hébergé sur le S3 trawlwatch de clever cloud (lien dans le notion)

[back] add clipped_territorial_seas.csv to loaded files (dim_zones)

---

backend/bloom/routers/v1/metrics.py
backend/bloom/services/metrics.py

J'ai corrigé la méthode getVesselsInActivity (on comptait les excursions, pas les navires). Je me retrouve avec un nombre non aberrant de navires en activité pendant une période donnée (1464 au max).
@alexphiev @rv2931 @SebM42 
**-> Est-ce que le résultat de cette méthode va nous servir ?** ou faut-il remplacer la méthode par une méthode qui renvoie juste le nombre de navires actifs comme on en a parlé hier en réunion ?

fix getVesselsInActivity

---

backend/bloom/infra/repositories/repository_excursion.py
backend/bloom/routers/requests.py
backend/bloom/routers/v1/vessels.py
backend/bloom/services/metrics.py

Mise en conformité des tests datetime_range selon les endpoints + ajout pagination/order pour vessels/id/excrursions
#	backend/bloom/infra/repositories/repository_excursion.py #	backend/bloom/routers/v1/vessels.py

fix: datetime range endpoint + conformisation + pagination/roder sur vessels/id/excursions

---

backend/alembic/versions/2b9d9e61be30_metrics_add_category.py
backend/bloom/domain/metrics.py
backend/bloom/infra/database/sql_model.py
backend/bloom/infra/repositories/repository_metrics.py
backend/bloom/tasks/create_update_excursions_segments.py

Lié au #339
Ajout de zone_id et zone_category afin de permettre de pouvoir retrouver (si besoin) la zone identifiée au niveau de la table metrics
LE souci vient du fait qu'il est possibel de créer aujourd'hui des zone avec le même non et la même sub_category (null notamment), idéalement il est donc nécessaire d'avoir le nom de la catégorie (indirectement via type) ou directement vie cette nouvelel colonne category
Cas problématique par exemple: zone "Mer territoriale au large de la France en Atlantique, Manche et Mer du Nord" qui a deux catégories, mais même nom et sub_category=null
De plus cela permettra d'avoir des statistiques sur de nouvelles catégories de zones avant que celle-ci ne soient complètement prises en compte et typée via la colonne type dans fct_metrics; avoir …

Feat add zone id category metrics

---

backend/bloom/domain/metrics.py
backend/bloom/infra/database/sql_model.py
backend/bloom/infra/repositories/repository_vessel.py
backend/bloom/routers/v1/vessels.py

Feat #339 (qui a disparu)
Rajout du endpoint vessels/{vessel_id}/times-in-zones
Renvoie le temps passés par zones pour un bateau sur une période donnée
Paramètres:
- vessel_id
- start_at/end_at
- category
- sub_category
- order (by duration_total)
Valeurs renvoyées:
- zone_name: nome de la zone
- zone_category: categorie de la zone
- zone_sub_category: sous-categorie de la zone
- duration_total: durée total dans la zone
- duration_fishing: durée à pêcher

feat: API add endpoint vessels/id/times-in-zones from metrics data

---

backend/bloom/tasks/create_update_excursions_segments.py

correction de create_update_excursions_segments dans le cas ou le batch nous renvoie une unique position par mmsi

cas unique positon/mmsi dans batch

---

docker/frontend/dev.Dockerfile

Fixe #341 
omme préconisé dans les discussions, déplacement du COPY frontend dès le début avant exécution du nvm/npm install

fix: docker Error de compilation (bloquant pour Stack docker) => move COPY

---

docker-compose.yaml

ajout de dépendance et période de grace. mlagré tout, on maintient le triple test healthcheck car l'init du service postgis se fait en deux étapes et il peut arriver sur le helthcheck soit OK à la fin de l'init postgres, puis redevienne NOK au premier lancement lorsque PostGis s'initialise ensuite

[BACKEND][DOCKER] feat: docker compose improve backend services start postgis/redis

---

backend/alembic/versions/2e4561a69da9_task_execution_add_duration_position.py
backend/bloom/config.py
backend/bloom/infra/database/sql_model.py
backend/bloom/infra/repositories/repository_task_execution.py
backend/bloom/tasks/clean_positions.py
backend/bloom/tasks/create_update_excursions_segments.py
backend/bloom/tasks/load_spire_data_from_api.py

Fix #398 
Ajout des colonnes duration et position_count à la table task_executions et adaptation des tâches load_spire_data_from_api, clean_positions et create_update_excursions_segments
On obtient des choses comme ça
Le déploiement des cette évolutions est bloqué actuellement par l'issue #349 qui déclenche une erreur sur la tâche create_update_excursions_segments
C'est potentiellement possible d'appliquer cette évolution à partit du commit actuel en production, cela permettra d'attendre de résoudre le #349 
Ajout d'un mécanisme de syncrhonisation en cas de lancement de plusieurs load_spire_data_from_api en paralèlle sur plusieurs machines pour fiabiliser l'aquisition #404

398 improve db task executions traces
