.env.template, Makefile, Trawlwatcher.py, alembic/init_script/load_amp_data.py, alembic/init_script/load_positions_data.py, bloom/config.py
Fixed the dev environment databases using DockerCompose for launching postgresql microservices (postgres, pgadmin).
- Launch the dev Database with: `make launch-dev-db` (don't forget to do `make build` before to build the d4g/bloom image)
- Launch Streamlit without Docker with: `streamlit run Trawlwatcher.py ` 
**_TODO:_**
Now everything is working, need to fix **"KeyError: "['_sa_instance_state'] not found in axis"** in streamlit after clicking LOAD button in **Vessel_Exploration**
=> fixing docker dev environment

Makefile
Add tesks to dump db from dev or prod environments
=> Add DB dump tasks

.gitignore, Makefile, data/README.md, data/utils/merge_filter_wpi.py, data/utils/string2float_coordinates.py, data/utils/zone_around_point.py, docker-compose-load-data.yaml, src/alembic/init_script/load_amp_data.py, src/alembic/init_script/load_ports_data.py, src/alembic/versions/7962eee40abe_create_port_table.py
Reprise de la PR https://github.com/dataforgoodfr/12_bloom/pull/104
Mais en intégrant quelques modifications/correction en plus d'un rebase
=> add ports to db (v2)

docs/notes/tasks.md, src/bloom/domain/vessel_data.py, src/bloom/domain/vessel_voyage.py, src/bloom/infra/repositories/repository_vessel_data.py, src/bloom/infra/repositories/repository_vessel_voyage.py, src/bloom/tasks/update_vessel_data_voyage.py
Ajout du traitement d'alimentation des tables des données statiques (`vessel_data`) et de voyage (`vessel_voyage`) à partir des données AIS.
=> Vessel data voyages

src/bloom/infra/repositories/repository_port.py, src/bloom/services/geo.py, src/tests/test_vessel_is_in_port.py
Ajout d'une fonction 'find_positions_in_port_buffer' dans 'src/bloom/infra/repositories/repository_port.py' permettant d'assigner les ports d'une liste de positions de navires en une seule requête à la DB.
=> [FEAT]: added function find_positions_in_port_buffer + unit test

src/bloom/infra/repositories/repository_task_execution.py
=> Fix issue 144

src/alembic/versions/4e912be8a176_alter_dim_vessel_gestion_maj_tracking.py, src/bloom/domain/vessel.py, src/bloom/infra/database/sql_model.py, src/bloom/infra/repositories/repository_vessel.py, src/bloom/tasks/clean_positions.py, src/bloom/tasks/load_dim_vessel_from_csv.py, src/bloom/tasks/load_spire_data_from_api.py, src/bloom/tasks/update_vessel_data_voyage.py
Implémentation de la gestion des mises à jour de la table vessel (cf issue #140 )
=> Feature maj dim vessels issue 140

backend/alembic/versions/06bb3c26076f_rename_fct_segment_head.py, backend/bloom/domain/segment.py, backend/bloom/infra/database/sql_model.py, backend/bloom/infra/repositories/repository_segment.py, backend/poetry.lock
=> Renommer la colonne fct_segment.head 

backend/bloom/infra/repositories/repository_port.py, backend/bloom/infra/repositories/repository_spire_ais_data.py, backend/bloom/infra/repositories/repository_vessel.py, backend/bloom/tasks/clean_positions.py
Ajout d'une fonctionnalité de traitement des données SPIRE AIS par lot de dates (par exemple: 7 jours)
=> Add clean position batch time

backend/bloom/tasks/create_update_excursions_segments.py
=> Gestion des Nan #180

backend/bloom/app.py, docker-compose.yaml
Application partielle des modifications liées au déploiement
principalement renommage main.py => app.py + adaptation docker-compose
=> mod: apply deployment mods main => app

README.md, backend/pyproject.toml, clevercloud/clever.json, docker/Dockerfile
Quelques ajustements (dont le passage à `uv`) pour pouvoir déployer les 2 apps sur les environnements Clever.
=> Deploy back & front end

backend/bloom/app.py
Add CORS middleware to enable access from local frontend
=> feat: add CORS middleware

backend/bloom/domain/zone.py, backend/bloom/infra/repositories/repository_zone.py, backend/bloom/routers/v1/zones.py
Version allégée du routeur get all zones, sans les géométries
=> feat: add zone summary

backend/bloom/domain/port.py, backend/bloom/infra/repositories/repository_port.py
Following #278, to be able to get the list of ports without timeout
=> feat: remove geometry from port

backend/bloom/infra/repositories/repository_vessel.py, backend/bloom/routers/v1/vessels.py, backend/bloom/routers/v1/zones.py
Issue #274 
Ajout des routeurs sous forme de liste
@router.get("/vessels/types")
@router.get("/vessels/classes")
@router.get("/vessels/countries")
renommage /zones/all/categories => /zones/categories
=> feat: 274 api listes valeurs types, classes, countries

frontend/components/core/map/main-map.tsx
=> change basemap URL

backend/bloom/services/metrics.py
[API] Endpoint /visiting-time-by-vessel 500 Internal Server Error #306
=> fix: #306  [API] Endpoint /visiting-time-by-vessel 500 Internal Server Error

backend/bloom/services/metrics.py
linked #309 
Changement de requête pour avoir le temps passé dans des MPA (aggrégation de segment in_mpa = True) sur la tranche de date données
=> fix: 309 change top vessel activity for activity in MPAs

frontend/components/core/map/main-map.tsx
=> Made zone click event do nothing

frontend/components/core/map/main-map.tsx, frontend/package.json, frontend/types/zone.ts
Related to https://github.com/dataforgoodfr/12_bloom/issues/289
=> Added map zone colors and borders

frontend/services/backend-rest-client.ts, frontend/services/dashboard.service.ts
=> Add vessels-at-sea total to dashboard

backend/bloom/domain/metrics.py, backend/bloom/tasks/create_update_excursions_segments.py
la branche est réparée @rv2931 tu peux tester maiq ded mon coté ça tourne
=> Metrics processing rebased

docker/build.sh, docker/down.sh, docker/up.sh
Ajout de scripts docker/build|down|up.sh
A utiliser de n'importe quel répertoire => <project_path>/docker/up.sh
Possibilité d'ajouter un paramètre
Pour compiler que le backend par exemple
<project_path>/docker/build.sh bloom-backend
Pour lancer que le backend par exemple
<project_path>/docker/up.sh bloom-backend
=> add: docker build/down/up script for Linux

backend/bloom/tasks/create_update_excursions_segments.py
fix miles to nautical in create_update_excursions_segments
=> fix miles to nautical
